modLoader = "kotlinforforge"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/${github}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[["dependencies.${mod_id}"]]
modId = "neoforge"
mandatory = true
ordering = "NONE"
side = "BOTH"

[["dependencies.${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${mc}"
ordering = "NONE"
side = "BOTH"